name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
type: bug
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!

    - type: dropdown
      id: story_points
      attributes:
          label: Story Points
          description: How many story points do you think the work is worth?
          options:
              - 1
              - 2
              - 3
              - 5
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: "A bug happened!"
      validations:
          required: true
