name: Generate Changelog Slides

on:
    workflow_dispatch: # Manual trigger
    schedule:
        - cron: "0 13 * * MON" # Every Monday around 8am cst, filtered further in js

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: 🟢 Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: 📦 Install dependencies
              run: yarn

            - name: 🔐 Set up Google credentials
              run: |
                  mkdir -p .github/scripts
                  printf "%s" '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > .github/scripts/googleCredentials.json

            - name: 🚀 Run changelogSlides.ts
              run: yarn run monthly:release:slides
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  CANNY_API_KEY: ${{ secrets.CANNY_API_KEY }}
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
